### ISSUE TITLE
Support for Cross Origin Resource Sharing (CORS)

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/docs-api#10]
Hi All,

First of all, thanks for this wonderful initiative.

I did some initial tests with the API and noticed that it does not return any headers for Cross Origin Resource Sharing (CORS, https://developer.mozilla.org/pt-PT/docs/Web/HTTP/CORS).

Do you plan to support CORS in the future?
I am planning to build an offline first Progressive Web App sometime in the future and this would be a big blocker for using the API from this type of app.

Best Regards,
Guilherme.

**Comment by daveajones** [comment]
Sure.  It's no problem to set that up.  What's your time frame?

**Comment by dellagustin** [comment]
Thanks a lot for the prompt response.
No planned time frame at this moment, still just experimenting and finding out and trying to address potential blockers early on.

**Comment by dellagustin** [comment]
So, as far as I could see this was already implemented, so I am closing the issue.
Thanks!
