### ISSUE TITLE
Authenticate-free way of getting a feed and item information by GUID?

### ISSUE THREAD

**Issue by ericpp** [Podcastindex-org/docs-api#108]
In the last PC2.0 boardroom, Adam wished that he could see which donations were attached to which artists he was streaming in Helipad. It seems like this the easiest way to do this would be to use the API to lookup the feed and item information and display it in Helipad. Unfortunately, both of those endpoints require authentication and since the Helipad code is open source, it would require either asking the user for an API key or embedding an API key with the software and hoping nobody uses it for evil.

Is there a way within the API or otherwise to obtain feed and item information by GUID without authentication?

**Comment by daveajones** [comment]
Hmm. Might need to make the v4v endpoints open then. Let me think it over if there’s any side effects. I think it’s prob ok.

**Comment by ericpp** [comment]
I'm using this endpoint for now for Helipad: https://podcastindex-org.github.io/docs-api/#get-/value/byepisodeguid
