### ISSUE TITLE
Are URLs to podcasting platforms returned from the API?

### ISSUE THREAD

**Issue by sangonzal** [Podcastindex-org/docs-api#114]
Hi, first of all, thanks for all of the great work on the project!

Does the Episodes API return URLs for some of the bigger podcast players (apple podcasts, Spotify, Google podcasts, etc)? Bard/ChatGPT seem to think it does, but I was reading through the documentation but couldn't find these fields anywhere.

**Comment by daveajones** [comment]
No, we don't return that type of thing.
