### ISSUE TITLE
Recent items can't walk successively older recent items

### ISSUE THREAD

**Issue by vandys** [Podcastindex-org/docs-api#12]
There probably needs to be an extra optional URL argument "before=<id>".  The query returns recent items, starting at the next one older than <id> (and you can have exclude still apply, etc.).  This lets a client walk back in time lazily, as needed to support a given user's actions.

**Comment by daveajones** [comment]
"before" would be a timestamp or an item id?

**Comment by vandys** [comment]
Ah, you have put your finger right on it.  IF each item is guaranteed to have a unique timestamp, timestamp is OK.  I don't know how your backend is put together, thus I was specifying ID, so you can calculate your search order in any fashion, and just continue yielding results past the point of that item.  So if you have unique timestamp, then a timestamp works OK.  Depending on how you got that timestamp, it's possible to have more than one item (submitted in a tight window) with the same value.

(BTW, depending on your perspective, you could justifiably call it "after")

**Comment by daveajones** [comment]
Fixed with 84c8a32ff3fbdc78edd353e0b64ba6fe21471584
