### ISSUE TITLE
Requesting API Endpoint via SST

### ISSUE THREAD

**Issue by gazishahi** [Podcastindex-org/docs-api#127]
Hey all, I have been trying to make requests to the API through setting up an endpoint with SST, however, I keep running into the same error:

`The hash in the Authorization header doesn't match up.  Please check your hash compute code: https://podcastindex-org.github.io/docs-api/#overview--authentication-details`

There appears to be no issue with the code, as I've used the example Node.js code and even the Node.js package, to no avail. I ran into the same error when trying to make an API call through Cloud Functions in Back4App. Any help would be greatly appreciated.

**Comment by stevencrader** [comment]
Please check that you are using a User-Agent different from the examples. Many of the samples have been blocked.

**Comment by gazishahi** [comment]
Yes, I have changed it and I am still running into the same error. The Node.js package has it set to `podcastdx client/1.0` and with the sample code I changed it to `sst aws`.

**Comment by stevencrader** [comment]
Can you share the example code you are referencing? I'll investigate.

**Comment by gazishahi** [comment]
The code I was referencing is [here](https://github.com/ComicStrip/node.js-podcastindex-org-example/blob/main/index.js). I thought it would be a timing issue as that made the most sense but logging the current UTC epoch time with `Date.now()` shows that it is within the 3 minute window. The Node.js package I was trying out is [here](https://www.npmjs.com/package/podcastdx-client), but it was also failing for me.

**Comment by stevencrader** [comment]
When I run the first example locally with node v22.0.0 and the following files, it returns a result for me. 

1. Create a `package.json` with
```json
{
  "module": "true",
  "dependencies": {
    "crypto": "^1.0.1"
  }
}
```
2. Create a `index.js` with the following. Replace the key and secret. Also notice the `User-Agent` change from the example.
```javascript
let crypto = require('crypto');

// ======== Required values ========
// WARNING: don't publish these to public repositories or in public places!
// NOTE: values below are sample values, to get your own values go to https://api.podcastindex.org 
const apiKey = "REPLACE";
const apiSecret = "REPLACE"
// ======== Hash them to get the Authorization token ======== 
const apiHeaderTime = Math.floor(Date.now() / 1000); //console.log(`apiHeaderTime=[${apiHeaderTime}]`);
const sha1Algorithm = "sha1";
const sha1Hash = crypto.createHash(sha1Algorithm);
const data4Hash = apiKey + apiSecret + apiHeaderTime;
sha1Hash.update(data4Hash);
const hash4Header = sha1Hash.digest('hex');
console.log(`hash4Header=[${hash4Header}]`);
// ======== Send the request and collect/show the results ======== 
let options =
    {
        method: "get",
        headers: {
            // not needed right now, maybe in future:  "Content-Type": "application/json",
            "X-Auth-Date": "" + apiHeaderTime,
            "X-Auth-Key": apiKey,
            "Authorization": hash4Header,
            "User-Agent": "StevenTest/1.8"
        },
    };
const query = "bastiat";
const url = "https://api.podcastindex.org/api/1.0/search/byterm?q=" + query;
fetch(url, options)
    .then(res => res.json())
    .then(json => {
        console.log(json);
    });

```
3. Run `npm install`
4. Run the file `node index.js`

**Comment by stevencrader** [comment]
For the `podcastdx-client`, it also works for me when run locally with Node v22.0.0. 

When I run the first example locally with node v22.0.0 and the following files, it returns a result for me. 

1. Create a `package.json` with
```json
{
  "module": "true",
  "dependencies": {
    "podcastdx-client": "^5.1.0"
  }
}
```
2. Create a `index.js` with the following. Either create a `.env` or set the environment variables for the key and secret or set them in the code. I don't see a way in the library to change the user agent but the default one it uses worked for me.
```javascript
const PodcastIndexClient = require("podcastdx-client");

// assumes you have an your key and secret set as environment variables
const client = new PodcastIndexClient({
    key: process.env.API_KEY,
    secret: process.env.API_SECRET,
    // opt-out of analytics collection
    disableAnalytics: true,
});

client.search("javascript").then(console.log);

```
3. Run `npm install`
4. Run the file `node index.js`

**Comment by stevencrader** [comment]
For use with SST, you will probably want to use the version without the library so you can pass the header fields directly to the `fetch` call. I have not used SST before so I don't know the steps for that.

**Comment by gazishahi** [comment]
Yes, I'm able to get it running locally as well, without an issue. I'm not sure why I'm running into this error, as I've followed the documentation for both PodcastIndex and SST closely. I'm also getting `Error: Unexpected token 'T', "The hash i"... is not valid JSON` as an error, which appears to be the same error (401). SST is Node.js based so I assumed it would work just fine with the example code.

**Comment by gazishahi** [comment]
I've been able to resolve the issue. It was with how SST stores secrets. Part of my secret was discarded when I used `npx sst set secret` as variables with `$` in the actual value need to be escaped with `\$`. Without using `\$`,  SST treats any characters after a `$` as an expandable variable. Thank you for the help!
