### ISSUE TITLE
Status Value is String not Enum

### ISSUE THREAD

**Issue by DavidBucienski** [Podcastindex-org/docs-api#131]
For several API calls the SCHEMA indicates status's value is **enum**. However, the value is a **string** as shown in the associated EXAMPLE for a given call. 

I have reviewed the server's response for a Trending call and can confirm it is a **string**. I would imagine this true for all calls with a status key-value pair. 

For all calls where present, **status: enum** should read **status: string**.

**Comment by stevencrader** [comment]
Can you give an example of a field that is incorrect? My review of all our `enum` types seems to match the [spec](https://swagger.io/docs/specification/v3_0/data-models/enums/). I would by happy to make changes if needed. 

If there are fields where more values than listed in the enum are possible, please share the API request with me and I'll update the spec.

Thanks

**Comment by DavidBucienski** [comment]
Okay, I see. The values for status are a predefined set of strings and thus status is an enum. 

You're right, never mind.
