### ISSUE TITLE
Reduce code example locations

### ISSUE THREAD

**Issue by comster** [Podcastindex-org/docs-api#15]
Code examples are currently located in 3 separate locations:

- Docs section: [Example Code](https://github.com/Podcastindex-org/docs-api#example-code)
- Example Code [repo](https://github.com/Podcastindex-org/example-code)
- Individual [repo's](https://github.com/Podcastindex-org?q=org-example)

They should be centralized (de-duped/linked).  Also, a best practice is to show `curl` as a vanilla example and libraries for language specific implementation.

**Comment by daveajones** [comment]
Yep.  It's bugging me to.  Will consolidate all to the docs, with links to the repos at the bottom.

**Comment by daveajones** [comment]
Created a new org for the example code:  https://github.com/Podcastindex-org-Examples
