### ISSUE TITLE
400 - "Bad Request" errors

### ISSUE THREAD

**Issue by zettadam** [Podcastindex-org/docs-api#20]
Not sure if this is the best place to post it but since I don't see a repo for the API backend I thought I might add it here. I'm getting frequent errors when using API that return a message:

`invalid json response body at https://api.podcastindex.org/api/1.0/search/byterm?q=javascript reason: Unexpected end of JSON input`

This happens when I use API directly from Postman and when I use Google Cloud Functions or my local NodeJS/Express app that I wrote. Sometimes API request returns a 200 response with results, but 75% of the time I see these errors.

When I use API directly with Postman, the response is an HTML page with "Bad request" heading. When I use NodeJS (either with Cloud Functions or with my ExpressJS app), I get an HTTP error with the message above.

Below is code from my ExpressJS app:

```
require('dotenv').config()

const express = require('express')
const cors = require('cors')
const bodyParser = require('body-parser')
const fetch = require('node-fetch')
const crypto = require('crypto')

const PORT = 2345

// Podcast Index
const API_BASE_URL = process.env.API_BASE_URL
const API_KEY = process.env.API_KEY
const API_SECRET = process.env.API_SECRET

const ts = Math.floor(Date.now() / 1000)
const authString = `${API_KEY}${API_SECRET}${ts.toString()}`
const authHeader = crypto.createHash('sha1').update(authString).digest('hex')

const headers = {
  'Content-Type': 'application/json',
  'User-Agent' : "AdamZ's homemade podcast-fetcher 0.01a",
  'X-Auth-Date': ts,
  'X-Auth-Key': API_KEY,
  'Authorization': authHeader
}

const server = express()

server.use(cors())
server.use(bodyParser.urlencoded({ extended: true }))
server.use(bodyParser.json())
server.use(bodyParser.raw())

server.post('/search/term', async (req, res, next) => {
  const { term } = req.body

  const url = `${API_BASE_URL}search/byterm?q=${term}`

  try {
    const results = await fetch(url, { headers })
    const data = await results.json()
    res.json({
      message: `Podcasts by term: ${term}`,
      data
    })
  } catch (err) {
    next(err)
  }
})

server.listen(PORT, (err) => {
  if (err) {
    console.error(err)
  } else {
    console.log(`Podcastindex server is listening on port: ${PORT}`)
  }
})
```

**Comment by daveajones** [comment]
Thank you for reporting. Can you email me your API key so I can check the logs:  dave@podcastindex.org

**Comment by daveajones** [comment]
Here's the triggering code: 
![image](https://user-images.githubusercontent.com/1498236/93717374-fbd5f700-fb3a-11ea-9ae5-b18d844848fa.png)

Something is keeping the query parameter from coming through.

**Comment by zettadam** [comment]
Hmm... but querystring is supplied according to docs?

```
https://api.podcastindex.org/api/1.0/search/byterm?q=javascript
```

**Comment by zettadam** [comment]
Got it fixed. Thanks @daveajones for helping me identify it.

The issue had to do with the fact that I was generating request headers on server startup and not for each separate request, as it should have been. 'X-Auth-Date' and 'Authorization' headers are time sensitive and have to regenerated for every request.

Here's updated code (I created a function to generate headers which I'm using in each request):

```
const generateHeaders = () => {
  const ts = Math.floor(Date.now() / 1000)
  const authString = `${API_KEY}${API_SECRET}${ts.toString()}`
  const authHeader = crypto.createHash('sha1').update(authString).digest('hex')

  return {
    'Content-Type': 'application/json',
    'User-Agent' : "AdamZ's homemade podcast-fetcher 0.01a",
    'X-Auth-Key': API_KEY,
    'X-Auth-Date': ts,
    'Authorization': authHeader
  }
}

server.post('/search/term', async (req, res, next) => {
  const headers = generateHeaders()
  const { term } = req.body
  const url = `${API_BASE_URL}search/byterm?q=${term}`

  try {
    const results = await fetch(url, { headers })
    const data = await results.json()
    res.json({
      message: `Podcasts by term: ${term}`,
      data
    })
  } catch (err) {
    next(err)
  }
})
```
