### ISSUE TITLE
(How to contribute to) stop words list

### ISSUE THREAD

**Issue by keunes** [Podcastindex-org/docs-api#23]
Hi
I was just listening to the [third episode](http://l.curry.com/fjd) of the podcast and got interested by the idea of a stop words list. Full description search would be cool, and as I understand from what you discussed, a good stop word list is a must to filter out irrelevant, generic words. Also it's one of the things I could help with as a non-programmer :)

Do such lists exist already, which could be used and expanded? Could/Should we already start building such lists ahead of an introduction of full search?

I imagine it could be helpful to have a simple text file that we can all contribute to here on GH (via PRs), but one per language to make it easier to manage (e.g. it'd be easier for me to review the list with Dutch only, rather than a massive list that includes German, English and Swahili words).

Thanks for this great work! (And sorry for posting this in the API Repo, didn't see any other that seemed fitting.)

**Comment by daveajones** [comment]
I think a community built stopwords list is a great idea.  I'll put up a repo for it.  Are you comfortable with using github and doing pull requests and such?

**Comment by keunes** [comment]
@daveajones Didn't notice your reply, sorry. Yes, I can use hit & PRs (through the web interface - that's quite straightforward). Will have a look!

**Comment by keunes** [comment]
Found it: https://github.com/Podcastindex-org/search

Thanks!
