### ISSUE TITLE
Episode.feedId has become Episode.feedid?

### ISSUE THREAD

**Issue by comster** [Podcastindex-org/docs-api#28]
I noticed this broke my unit test in my js library for "Episodes By Feed Id"

Maybe it's just a typo or perhaps a change in case?

**Comment by daveajones** [comment]
Let me check.  Could be a typo.

**Comment by daveajones** [comment]
I don't see any breaking changes.  It still works like it always has.  I looked at your unit test and it seems to be defined correctly.  Not sure.  How is it breaking?  What's the failure you're seeing?

**Comment by Siebe** [comment]
Can confirm. The episode objects in the output for api/1.0/episodes/byfeedid used to have a key called "feedId". This is now changed in "feedid".  My guess is this is why the test fails.
Also, if i'm not mistaken the key "feedTitle" has been removed entirely.

**Comment by comster** [comment]
Ya, js variables are case-sensitive and it seemed like it changed from `feedId` to `feedid`.

I can't confirm the `feedTitle` change, but I too was looking to use it via Episode and also noticed it wasn't there.

**Comment by daveajones** [comment]
Ah, my bad.  I misunderstdood.  You were talking about the output, not the url.  Let me check.

**Comment by daveajones** [comment]
Ok, fixed. Please confirm it looks right on your side now.

@Siebe I don't see any record of ever having feedTitle in that call response.  Do you need it?

**Comment by Siebe** [comment]
I'm pretty sure feedTitle used to be in there as well, and perhaps even feedLanguage?
I believe @RyanHirsch keeps a neatly overview in typescript
https://github.com/RyanHirsch/podcastdx-client/blob/master/src/types.ts

And no, I don't need it. I just wouldn't recommend changing or removing keys, only adding new ones. Until you you version up of course.

**Comment by daveajones** [comment]
I see those being returned in "recent/episodes" but not in the commit history of "episodes/byfeedid".  I wonder if he synthesized from that.  Regardless, they should probably match.  I'll make that change.

**Comment by RyanHirsch** [comment]
Yes I've found some gaps in my types. I'm going to try and address them today.

**Comment by daveajones** [comment]
Seems like this is solved so I'm going to close this.
