### ISSUE TITLE
Blank/empty categories being returned by search

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/docs-api#35]
Looking at https://api.podcastindex.org/api/1.0/search/byterm?q=podnews

This query is returning an empty category for some feeds.

As an example, for the German-language id 1188972 ("podnews.de (Feed aller Podcast-Folgen)") it returns:
`"categories":{"9":"Business","55":"News","56":"Daily","102":"Technology","":""}`

The last, blank, pair of ID/category should probably not be there.

**Comment by daveajones** [comment]
10-4. Will go bug hunting. I have an idea what it is.

**Comment by daveajones** [comment]
Fixed.
