### ISSUE TITLE
Entries submitted by iTunesID not with iTunesID 

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/docs-api#36]
"PODNEWS Mx" seems brand new in Apple iTunes, with an ID 1536114728.

My script successfully added it at :44 using `https://api.podcastindex.org/api/1.0/add/byitunesid` - here's my logfile entry
```
2020-10-28 03:44:15: PODCASTINDEX INSERT FROM SEARCH PODNEWS Mx {"status":"true","feedId":1319023,"existed":"false","description":"Feed added successfully. Please allow 15-20 minutes for it to be searchable in the index."}
```

It's now in PodcastIndex under 1319023 - but the response appears not to include the iTunesID. Here's the chunk I'm pulling out of the API

```
 "title":"PODNEWS Mx",
         "url":"https:\/\/anchor.fm\/s\/29f8d170\/podcast\/rss",
         "originalUrl":"https:\/\/anchor.fm\/s\/29f8d170\/podcast\/rss",
         "link":"https:\/\/anchor.fm\/marco-edivaldo",
         "description":"Como est\u00e1n mis queridos amantes de los podcast, les damos la bienvenida a PODNEWS , el mejor canal de la plataforma con las mejores noticias del planeta, en donde seg\u00fan Andr\u00e9s Carrera y yo Marco Edivaldo se deben contar.",
         "author":"Marco Edivaldo",
         "ownerName":"Marco Edivaldo",
         "image":"https:\/\/d3t3ozftmdmh3i.cloudfront.net\/production\/podcast_uploaded\/6941724\/6941724-1602803535283-b589817b185bc.jpg",
         "artwork":"https:\/\/d3t3ozftmdmh3i.cloudfront.net\/production\/podcast_uploaded\/6941724\/6941724-1602803535283-b589817b185bc.jpg",
         "lastUpdateTime":1603856680,
         "lastCrawlTime":1603856680,
         "lastParseTime":1603856681,
         "lastGoodHttpStatusTime":1603856680,
         "lastHttpStatus":200,
         "contentType":"application\/rss+xml; charset=utf-8",
         "itunesId":null,
         "generator":"Anchor Podcasts",
         "language":"es-mx",
         "type":0,
```

Given that I added this script using `https://api.podcastindex.org/api/1.0/add/byitunesid` it should include the iTunesID, yes?

Further attempts to submit it via `https://api.podcastindex.org/api/1.0/add/byitunesid` - since my script doesn't know it exists in the database - are now returning blank responses by the looks of things.

**Comment by jamescridland** [comment]
I should also drearily say that I'll be submitting a DMCA takedown request for "PODNEWS Mx" using [Anchor's DMCA form](https://docs.google.com/forms/d/e/1FAIpQLSeJozDjcrtHuDvq36cIqB_YIZhwxOSnjnAUuVXUCXsYG_l_TA/viewform), since it is not an authorised use of the Podnews&reg; trademark.

**Comment by daveajones** [comment]
I think I have this fixed now.  Resolving and linking the itunes id's to existing feeds, or creating if they don't exist is a complex dance on the back-end.  More complex than it should have been.  I've simplified it a lot.  There is still a queue so it's not immediate.  But it should be within the typical 20-30 minute window that a regular feed add is, after it goes through the checks.
