### ISSUE TITLE
API returns 400 http status code when no podcast or episode is found, and not CORS headers

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/docs-api#37]
Hello all,

the API is currently returning HTTP 400 (Bad Request) when the requested podcast or episodes or podcast is not found in the index.
400 usually means that the request is malformed, but it is not the case, it should probably be returning 404.

Additionally, when it returns 400, the CORS headers are missing, and thus access through the browser by other domains is not possible.

Use case: When importing OPML feeds I use the `podcasts/byfeedurl` to check if I can get the podcast information and later episodes from the feed.

Best Regards,
Guilherme.

**Comment by daveajones** [comment]
Thanks.  I'll check this out.

**Comment by daveajones** [comment]
Added CORS to all responses.
