### ISSUE TITLE
Empty categories for feed is an array, but with categories is an object

### ISSUE THREAD

**Issue by RyanHirsch** [Podcastindex-org/docs-api#39]
There's an odd type mismatch for feeds with empty categories compared to those without. Without categories, an empty array `[]` is returned (see: https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=233796), however for a feed with categories an object of `categoryId: categoryName` is returned (see: https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=183562)

I'm trying to produce JSON Schema definitions for the endpoints and this discrepancy is causing me some issues. If it is intentional, I'll try to work around it, but on the surface, it feels a little weird.

**Comment by daveajones** [comment]
It should probably return null to be consistent with the way other non-existent properties are returned. Agree?

**Comment by RyanHirsch** [comment]
That works for me

**Comment by RyanHirsch** [comment]
@daveajones ping on this (just so it doesn't fall off the radar)

**Comment by daveajones** [comment]
Got it. Still on the to-do list. Hope to get some coding time today. Thanks for the reminder.

**Comment by daveajones** [comment]
Should be fixed now.  Confirm?

**Comment by RyanHirsch** [comment]
Well, I've gotten further, now the same issue appears to be happening for `/api/1.0/search/byterm`.

**Comment by daveajones** [comment]
Ugh. My bad. The underlying call on that is different. Give me a minute to fix.

**Comment by daveajones** [comment]
Ok, should be good now.

**Comment by RyanHirsch** [comment]
Awesome, these first schema's are now valid! Now I need to do more. Thanks!

**Comment by pluto-dev** [comment]
Hey, this issue still seems to exist for following API endpoint:

https://api.podcastindex.org/api/1.0/podcasts/bytag

There a bunch feeds with  "categories": [ ]

**Comment by daveajones** [comment]
This should be fixed now.
