### ISSUE TITLE
Feature request for soundbites API

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/docs-api#41]
Hi All,

I want to use the recent soundbites API for discovery, but the API currently does not return the episode title nor the podcast name, so I don't have any human readable information to show (as the soundbite title is option, and in most tests with the API it currently comes empty).

Could you add more information to the results of the recent soundbites API? For me the idea would be (in order of importance to me):
1. episode title
2. podcast title
3. podcast feed url
4. podcast id

podcast feed url and id are not so important, as I don't need to show them to the user, I just need in case the user wants to subscribe to that podcast, so I can get it based on the episode id (already returned), with a call to the episode API.

**Comment by daveajones** [comment]
Sure. Will be as to add that info.

**Comment by daveajones** [comment]
Done!
