### ISSUE TITLE
Missing podcasts/trending

### ISSUE THREAD

**Issue by stevencrader** [Podcastindex-org/docs-api#48]
No documentation for `podcasts/trending`

**Comment by daveajones** [comment]
Thanks for putting these as issues. I have a couple of questions for you on it. Will post tomorrow.

**Comment by stevencrader** [comment]
You're welcome. I didn't want to forget about them.

**Comment by daveajones** [comment]
Ok, I'm getting confused on this.  Would it be too much trouble to get you to add the trending tag so I can see the diff of what all you changed?  I'm afraid I might be changing files that are products of the generation instead of the source.

**Comment by stevencrader** [comment]
The only files that are generated are `pi_api.json` and `pi_api.yaml` in the docs folder. The Postman file was originally generated but I had to do manual cleanup afterwards so I just hand modified it this time.
