### ISSUE TITLE
API Hole

### ISSUE THREAD

**Issue by gogman** [Podcastindex-org/docs-api#54]
There needs to be an API call to get the list of categories and a search feature that searches in a category/categories.

Here is my story:

As a Developer, I want to to provide my user with a selectable list of categories to search, so that the user may search for Podcast with the name "Agenda" and/or the person "Adam" or "John" in the "Comedy" and/or "Drama" categories.

**Comment by daveajones** [comment]
There is already a category list api.  It's not documented yet:

https://api.podcastindex.org/api/1.0/categories/list?pretty

There are various ways to filter on category by number or name.  I'll check and see where support is on the search side and post back.

**Comment by stevencrader** [comment]
The `/categories/list` endpoint is now documented

https://podcastindex-org.github.io/docs-api/#get-/categories/list

**Comment by daveajones** [comment]
Thanks Steven!

**Comment by gogman** [comment]
Thanks so much!
