### ISSUE TITLE
Always get time window error

### ISSUE THREAD

**Issue by walkero-gr** [Podcastindex-org/docs-api#62]
I am developing an application in C for AmigaOS 4, called MediaVault (https://github.com/walkero-gr/mediavault), and I want to add support for podcasts.

I use libcurl to make the calls and I add the headers as I should be doing, but unfortunately, I get all the time the "+/- 3 mins window" error, which I am not sure if this actually is the problem or something else. I double-triple checked the authorization header and the information that is in there, and still get the same message.

So, my question is, if there is a way to see a log of the request is it is received by your servers, or if there is a way to find more information why this fails.

Thank you so much for your help and time.

**Comment by daveajones** [comment]
You must recalc the auth hash and set a new date header for each call. Are you doing that?

**Comment by walkero-gr** [comment]
@daveajones 
Thank you so much for your fast reply.
I absolutely do that. Every time I do a new request to the api, I create the authorization with the new timestamp.
If anything else was the problem, should I get a different error message?
What would be helpful would be a way to see the actual request the API gets. Something like a requests log at the backend. With the headers and all the data, and the response code somewhere. Even if it was just a plain log file shown at a page. Is this possible?

**Comment by daveajones** [comment]
I put in some debug for this specific issue.  Try it again.  I'll look at giving back more detail once I get some other stuff off my plate.

**Comment by walkero-gr** [comment]
@daveajones 
That is awesome. Here is the output I got on the request.
This Server time means that this is the one that is compared the request time to?


```
X-Auth-Date header value is not within the +/- 3 minute time window.  Please see: https://podcastindex-org.github.io/docs-api/#overview--authentication-details

Debug
  Server time: 1631642994

Headers Received
  X-Auth-Date: 1631646658
  X-Auth-Key: CWN8YHEYKJDRPRE6PQSH
  Authorization: 458c17b485e1e63931b7b020ae6821c051574115
  User-Agent: MediaVault/1.3 (AmigaOS)
```

**Comment by stevencrader** [comment]
Is the time you are sending UTC or local time? I tried to look at your code but wasn't sure what `now()` returned.

**Comment by walkero-gr** [comment]
@stevencrader 
Thank you so much for taking a look. Actually it doesn't take care of the timezone, and it is the time of user's machine. This is something I should take in account? It should be based on UTC or something else?

**Comment by stevencrader** [comment]
I believe the time needs to be UTC epoch time. You can compare the time reported in your app to the time reported here https://www.epochconverter.com/

**Comment by walkero-gr** [comment]
@stevencrader 
That's great. At least now I can see what might be wrong. I will test it. and get back to you.

**Comment by walkero-gr** [comment]
@stevencrader I believe you are right. Changed my timestamp reducing by 1 hour, which is my timezone (UTC+1), and now I got data just fine.

I think that information must be added at the docs, for others to know.

Thank you both for your valuable help.

**Comment by daveajones** [comment]
Thanks guys.
