### ISSUE TITLE
Examples links do not work

### ISSUE THREAD

**Issue by dennisreimann** [Podcastindex-org/docs-api#66]
Examples links like https://api.podcastindex.org/api/1.0/search/byperson?q=adam%20curry&pretty do not work, yielding `Authorization header value either not set or blank.  Please see: https://podcastindex-org.github.io/docs-api/#overview--authentication-details`.

**Comment by daveajones** [comment]
You must be logged in to the api server with a web session for those links to work with from a web browser.

**Comment by dennisreimann** [comment]
Thanks for clarifying that -- now it works for me!
