### ISSUE TITLE
Moving the official docs here

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/docs-api#8]
I'm no markdown pro, so if anyone wants to get in and clean this file up and make it look pretty, I'll just change the links on the site to point here instead of internal since this document is getting better.  I like the clickable live look at what the responses should look like, but I can make some dummy responses to link to instead.

**Comment by comster** [comment]
I think the easiest thing todo first is just to enable this repo master branch with GitHub Pages: https://pages.github.com/

It will just turn the README.md file as a hosted html page with a URL: http://podcastindex-org.github.io/docs-api

For instance on my fork using the "slate" theme looks like this: https://comster.github.io/docs-api/

Then any changes are auto update / reflected there.

I'll also do a quick pass on the readme to make the URLs links as you've mentioned.

**Comment by daveajones** [comment]
Perfect way to handle. Will do.

**Comment by daveajones** [comment]
Done. Will merge your changes and then good to go. I’ll up date the links on the dev portal to point here.
