### ISSUE TITLE
ByTerm Search "Atari"

### ISSUE THREAD

**Issue by DavidBucienski** [Podcastindex-org/docs-api#80]
The search term "Atari" up until recently would return a bunch of podcasts about the Atari game console. Now when doing a byTerm search for Atari, I get a bunch of Spanish podcasts that don't appear to have any connection to the game console. Atari game console podcasts are no longer easily discoverable.

**Comment by stevencrader** [comment]
@daveajones did something change with the search? It seems to match partial words. Ex: Gataric, Tatari, Catarina, etc.

https://podcastindex.org/search?q=Atari

**Comment by daveajones** [comment]
Yes I changed it in response to this:  https://podcastindex.social/@snowninja/108963242403460050

 I will change it back and implement this as an optional parameter.

**Comment by DavidBucienski** [comment]
Good plan, thanks.

**Comment by daveajones** [comment]
I rolled the search change back.

**Comment by DavidBucienski** [comment]
I can confirm it responds properly now.
