### ISSUE TITLE
Request: return the podcast GUID in /podcasts/byitunesid

### ISSUE THREAD

**Issue by jamescridland** [Podcastindex-org/docs-api#83]
Hello! 

It would be a great help if the results of the `/podcasts/byitunesid` matched the results of `podcasts/byfeedid` (and by guid).

Specifically, I've noticed that the /byitunesid call does not return the `podcastGuid`.

Test URLs:

https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=473264&pretty

https://api.podcastindex.org/api/1.0/podcasts/byitunesid?id=1246288327&pretty

**Comment by daveajones** [comment]
Fixed!
