### ISSUE TITLE
Include socialInteract (comments) data on the episodes returned by the API

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/docs-api#91]
## References
- Related Mastodon threads
    - https://fosstodon.org/@dellagustin/109706951648637618
    - https://podcastindex.social/@dave/109837162459570961

**Comment by daveajones** [comment]
Oh I see you added here already. 👍

**Comment by dellagustin** [comment]
> Oh I see you added here already. 👍

It is not everyday I can say I was one step ahead of @daveajones 😂

**Comment by dellagustin** [comment]
Hi @daveajones , I just tested with Podcasting 2.0 (http://mp3s.nashownotes.com/pc20rss.xml, id=920666).
For `/episodes/byfeedid` it is not returning `socialInteract`.
For `/episodes/byid`, it is returning `socialInteract`, but `protocol` is a number instead of the corresponding value in the feed (`activitypub`).

```json
"socialInteract": [
            {
                "uri": "https://podcastindex.social/@dave/109722964424091177",
                "protocol": 1,
                "accountId": "@dave",
                "accountUrl": "https://podcastindex.social/users/dave",
                "priority": 0
            }
        ],
```

**Comment by daveajones** [comment]
Still working on it. Should be finished up today.

**Comment by dellagustin** [comment]
Tested and it is working.
